
version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/transactions
      AWS_ENDPOINT_URL: http://localstack:4566
      SQS_QUEUE_URL: http://localstack:4566/000000000000/transactions
    depends_on:
      - db
      - localstack

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/transactions
      AWS_ENDPOINT_URL: http://localstack:4566
      SQS_QUEUE_NAME: transactions
    depends_on:
      - localstack

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - DEBUG=1
    ports:
      - "4566:4566"
